### ISSUE TITLE
Update Tests

### ISSUE THREAD

**Issue by arb** [hapijs/bassmaster#32]
Updates test according to [this](https://github.com/hapijs/contrib/blob/master/Tests.md)

**Comment by cadecairos** [comment]
@arb can you clarify what needs to be updated here? 

Is it all the server setup that should be moved outside the describe block? (https://github.com/hapijs/bassmaster/blob/eec3ab7a4a8c2de0796143b7a587e84de039565b/test/batch.js#L27-L198)
