### ISSUE TITLE
Can you pass in options.auth to config.auth in the setup?

### ISSUE THREAD

**Issue by ericeslinger** [hapijs/bassmaster#35]
I've got my own fork of bassmaster that does this, which allows me to register the plugin with an auth strategy that applies to the entire /batch endpoint. That way I can return a 401 not authenticated on the batch route instead of fifty 401s in the response array which was a 200 when there's no token on the request.

I'm working on submitting a PR, but the test is a pain. I'm not sure how to properly mock a test authentication strategy, so Hapi can be given the config.auth string without complaining. I guess I could import bell and a bunch of other stuff to the test environment but that seems like overkill.

Anyway, if you've got advice about writing the test properly or whatever, I can submit this as a dead simple PR.

**Comment by Tatort79** [comment]
+1

**Comment by cadecairos** [comment]
Looks like this is supported already: https://github.com/hapijs/bassmaster/blob/8428742750fc2cc6409a57c32a049be7d615f8a6/lib/batch.js#L74

It's just undocumented.
