### ISSUE TITLE
hapi 8.0 API

### ISSUE THREAD

**Issue by hueniverse** [hapijs/bassmaster#37]

**Comment by ericeslinger** [comment]
Does this mean that bassmaster is incompatible with hapi8 right now? I have tried using both 1.6 and the 1.7 version that's on the hapi8 branch of this repo, and in both cases trying to register bassmaster is getting an error thrown out of Hapijs core (v 8.1.0 and 8.0.0). 

In particular:

    Possibly unhandled TypeError: Cannot read property 'register' of undefined
        at internals.Plugin.register (node_modules/hapi/lib/plugin.js:201:28)

This could be my fault as well - I may have missed the way to register plugins in the new 8.0 API interface, but `bell` is working just fine.

**Comment by ericeslinger** [comment]
Ah, nevermind- that was my own fault. Apparently since the 8.0 release, the hapi method of registering a plugin with an options hash changed from expecting an object with the plugin and options keys to expecting one with register and options.
