### ISSUE TITLE
Allow using nested object values when piplining

### ISSUE THREAD

**Issue by cadecairos** [hapijs/bassmaster#50]
I've got a case where a response looks like this:

```
{
  obj: {
    id: 1
  }
}
```

And I'd like to do this in a future batch request: "/foo/$0.obj.id/bar", but it seems I can only refer to one level of an object.

**Comment by cadecairos** [comment]
cc/ @hueniverse

**Comment by cadecairos** [comment]
This can be better accomplished with Hoek.reach

**Comment by hueniverse** [comment]
If the issue was already released, you need to open a new one. Otherwise we lose the history of what was included in each release.

**Comment by cadecairos** [comment]
you got it!
