### ISSUE TITLE
Refactor - Part Two

### ISSUE THREAD

**Issue by cadecairos** [hapijs/bassmaster#66]
There's lots of crazy code in Bassmaster.

For example: 
* Sharing index counter variables outside of for loops (improve with forEach, anonymous functions)
* for loops where `Array.prototype.some` or `Array.prototype.every` or `Array.prototype.forEach` would be better.

I'll probably find other things to optimize while refactoring.

The goal here is to rewrite things without changing any functionality, to improve readability of the code and reduce the likelyhood of bugs.

**Comment by devinivy** [comment]
> Sharing index counter variables outside of for loops

Using `let` will also scope those variables just within the loop :)

**Comment by cadecairos** [comment]
Block scoping the iterator with `let` [is used in a handful of places](https://github.com/hapijs/bassmaster/pull/67/files#diff-d63b253f4ac4a49ee08306581cd7b907R144), but in most cases the use of a [for loop is not required](https://github.com/hapijs/bassmaster/pull/67/files#diff-d63b253f4ac4a49ee08306581cd7b907R93) when tools like `forEach` or `every` exist.

**Comment by Marsup** [comment]
That depends on the performance you expect out of it, forEach is still way slower than a for loop. But then again that depends on how much elements you're iterating over.

**Comment by cadecairos** [comment]
You're right, it's definitely slower. I think in this case it's okay though because doing *tens of thousands* of requests in a single batch call would be... inadvisable, at least from me!
