### ISSUE TITLE
Question: Pipelining arrays

### ISSUE THREAD

**Issue by casalot** [hapijs/bassmaster#70]
The following works fine, when it is returning a single customer object:
```javascript
payload: '{"requests": [{"method":"GET","path":"/api/customers/' + request.params.id + '"},{"method":"GET","path":"/api/profile/$0.profileId"}]}'
```

How would I implement this for a response with an array of customer objects:
```javascript
payload: '{"requests": [{"method":"GET","path":"/api/customers"},{"method":"GET","path":"/api/profile/$0.profileId"}]}'
```

At the moment I'm getting HTTP500, when I try with the code above.

**Comment by brightloudnoise** [comment]
I had a similar issue and assume that the response you are getting from /api/customers has nested arrays. If that's the case you will need to use use $0.0.profileId to reach the profileId of the first customer returned.

**Comment by cadecairos** [comment]
> If that's the case you will need to use use $0.0.profileId to reach the profileId of the first customer returned.

This is correct, Bassmaster uses [Hoek.reach](https://github.com/hapijs/hoek/blob/master/API.md#reachobj-chain-options) when pipelining requests, so numbers in the chain will act like Array indicies.
