### ISSUE TITLE
Deprecate or migrate?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/bassmaster#76]
Is this still being used? Should we deprecate it? If not, please open a hapi v17 migration issue.

**Comment by temsa** [comment]
I always end up having this plugin in most of my services, because it is just so practical 👍 @cadecairos is creating a v17 version something you are likely to do ?

**Comment by cadecairos** [comment]
Hi @temsa I'll take a look at how much work the port will be.

**Comment by cadecairos** [comment]
porting is being explored in #78

**Comment by cadecairos** [comment]
@temsa  [Bassmaster v3.0.1](https://www.npmjs.com/package/bassmaster) now supports Hapi v17 - please test and let me know if anything isn't working like it should!

also see: [release notes](#80)
