### ISSUE TITLE
Support hapi v17

### ISSUE THREAD

**Issue by devinivy** [hapijs/bassmaster#77]
Would love to see this supported under v17.  I could possibly help with the upgrade if interested.  This issue is opened in response to #76.

**Comment by cadecairos** [comment]
see #78

**Comment by cadecairos** [comment]
@devinivy  [Bassmaster v3.0.1](https://www.npmjs.com/package/bassmaster) now supports Hapi v17 - please test and let me know if anything isn't working like it should.

also see: [release notes](#80)
