### ISSUE TITLE
Migrate to Hapi V17

### ISSUE THREAD

**Issue by cadecairos** [hapijs/bassmaster#78]

**Comment by dhinklexo** [comment]
This is blocking an upgrade for me to Hapi 17. This plugin has been super useful so I'd love to see it updated as well.

**Comment by cadecairos** [comment]
@dhinklexo [Bassmaster v3.0.1](https://www.npmjs.com/package/bassmaster) now supports Hapi v17 - please test and let me know if anything isn't working like it should.

also see: [release notes](#80)
