### ISSUE TITLE
Batching h2o2 request

### ISSUE THREAD

**Issue by palmerjc** [hapijs/bassmaster#84]
I am using the h2o2 module to proxy calls to an external web service and the individual service works just fine.  However, when I try to batch several of these calls together I end up getting a 504 error for each request (looking @ line 268 of batch.js).  Looking for any guidance as to why this might be.

**Comment by palmerjc** [comment]
I wanted to provide a correction - it does appear that the mapURI is getting called (had my step in the wrong location).  However, the call to the endpoint results in Gateway Timeout (504 error) when called via Bassmaster vs working correctly when endpoint is called directly.

**Comment by spanditcaa** [comment]
https://github.com/hapijs/h2o2/issues/77

**Comment by spanditcaa** [comment]
resolved in h2o2 8.1.1 https://github.com/hapijs/h2o2/commit/1799adbaa2eb837998a18b8c4da64bb57378bb2d
